from fastapi import APIRouter

from app.features.nuvemshop.nuvemshop_category_router import nuvemshop_category_router
from app.features.nuvemshop.nuvemshop_oauth_router import nuvemshop_oauth_router
from app.features.nuvemshop.nuvemshop_product_router import nuvemshop_product_router
from app.features.nuvemshop.nuvemshop_stock_router import nuvemshop_stock_router
from app.features.nuvemshop.nuvemshop_webhook_router import nuvemshop_webhook_router

router = APIRouter()

router.include_router(nuvemshop_oauth_router)
router.include_router(nuvemshop_webhook_router)
router.include_router(nuvemshop_stock_router)
router.include_router(nuvemshop_product_router)
router.include_router(nuvemshop_category_router)
